AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 50
    MemorySize: 5000
  Api:
    OpenApiVersion: 3.0.1
Parameters:
  Stage:
    Type: String
    Default: dev
  YourEmail:
    Type: String
    Default: lloyd.lm.hamilton@gmail.com
Resources:
  # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
  UserPool:
     Type: AWS::Cognito::UserPool #https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cognito-userpool.html
     Properties:
         AdminCreateUserConfig:
          AllowAdminCreateUserOnly: true
         UserPoolName: lambdausers
         UsernameAttributes:
         - email
         AutoVerifiedAttributes:
         - email
         Policies:
          PasswordPolicy:
              MinimumLength: 6
              RequireLowercase: true
              RequireNumbers: true
              RequireSymbols: true
              RequireUppercase: true
  UserPoolTokenClient:
     Type: AWS::Cognito::UserPoolClient
     Properties:
       UserPoolId: !Ref UserPool
       GenerateSecret: false
       ExplicitAuthFlows:
       - ALLOW_USER_PASSWORD_AUTH
       - ALLOW_REFRESH_TOKEN_AUTH
  UserPoolUser:
     Type: AWS::Cognito::UserPoolUser
     Properties:
       DesiredDeliveryMediums:
         - EMAIL
       Username: !Ref YourEmail
       UserPoolId: !Ref UserPool
  MyApi:
    Type: "AWS::Serverless::Api"
    Properties:
      StageName: !Ref Stage
      Auth:
        Authorizers:
          MyCognitoAuth:
            UserPoolArn:
              Fn::GetAtt:
                - UserPool
                - Arn
            AuthType: "COGNITO_USER_POOLS"
        DefaultAuthorizer: MyCognitoAuth
  # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  PredictFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        Predict:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /predict
            Method: POST
      Policies:
        - AmazonS3FullAccess
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
      DockerTag: python3.9-v1
Outputs:
  InferenceApi:
    Description: "API Gateway endpoint URL for Dev stage for Predict Lambda function"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/predict"
  UserPoolId:
    Description: "UserPool ID"
    Value: !Ref UserPool
  UserPoolTokenClient:
    Description: "UserPoolClient ID"
    Value: !Ref UserPoolTokenClient

