AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Timeout: 50
    MemorySize: 5000
  Api:
    OpenApiVersion: 3.0.1
Parameters:
  Stage:
    Type: String
    Default: dev
Resources:
  # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
  MyAuthFunctions:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri: ./authorizer
      Handler: handler.authorize
      Runtime: python3.9
  MyApi:
    Type: "AWS::Serverless::Api"
    Properties:
      StageName: !Ref Stage
      Auth:
        DefaultAuthorizer: MyAuthFunctions
        Authorizers:
          MyAuthFunctions:
            FunctionArn: !GetAtt MyAuthFunctions.Arn
            FunctionPayloadType: TOKEN
            Identity:
              # Must specify at least one of
              # Headers, QueryStrings, StageVariables, or Context
              Headers:
                - authorizationToken
              ReauthorizeEvery: 100
  # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
  PredictFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        Predict:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /predict
            Method: POST
      Policies:
        - AmazonS3FullAccess
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./
      DockerTag: python3.9-v1
Outputs:
  InferenceApi:
    Description: "API Gateway endpoint URL for Dev stage for Predict Lambda function"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/${Stage}/predict"
  InferenceFunction:
    Description: "Inference Lambda Function ARN"
    Value: !GetAtt PredictFunction.Arn
  InferenceFunctionIamRole:
    Description: "Implicit IAM Role created for Inference function"
    Value: !GetAtt PredictFunction.Arn